# Vim
export EDITOR="nvim"

# Flask
export FLASK_RUN_PORT=6000
export FLASK_APP="manage.py"
export FLASK_DEBUG=1

# Golang
export GOPATH="$HOME/.gopath"
export GO111MODULE="on"
export GOPROXY="https://goproxy.cn"

# Local PATH
export PATH="$PATH:$HOME/.local/bin"
export PATH="$PATH:$GOPATH/bin"

# VirtualenvWrapper
export WORKON_HOME="$HOME/.virtualenvs"

# GPG
export GPG_TTY=$(tty)

# Homebrew
export HOMEBREW_BOTTLE_DOMAIN="https://mirrors.ustc.edu.cn/homebrew-bottles"
export HOMEBREW_CASK_OPTS="--appdir=$HOME/Applications"

# Claude
export DISABLE_TELEMETRY=1
export DISABLE_ERROR_REPORTING=1
export DISABLE_NON_ESSENTIAL_MODEL_CALLS=1
